# Generated by Django 3.2.13 on 2022-10-08 01:34

from django.db import migrations


def copy_source_to_dest(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start, 
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()

def forward_course_abc_to_mti(apps, schema_editor):
    copy_source_to_dest(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )

def backward_course_abc_to_mti(apps, schema_editor):
    copy_source_to_dest(
        apps.get_model('core', 'Course'),
        apps.get_model('core', 'CourseOld')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(
            forward_course_abc_to_mti,
            backward_course_abc_to_mti
        )
    ]
